site_name: 博阳的魔法藏书室

repo_name: this repository
repo_url: https://https://github.com/YangOnlYKonws/mywiki

plugins:
  - search:
      lang: ja
      separator: '[\s\u200b\-]'


theme:
  name: 'material'
  language: zh
  static_templates:
    - 404.html

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: 切换到暗色
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: 切换到明色
nav:
  - 首页: index.md
  - 算法:
      - 数组排序: 算法/数组排序.md
  - 数据结构:
      - 矩阵: 数据结构/矩阵.md
  - Java:
      - 小项目（练手）: Java/Java贩卖机.md
  - 杂项:
      - mkdocs文件上传: 杂项/Mkdocs部署与上传.md
